### PR TITLE
Enable JITServer by default on supported platforms

### PR DESCRIPTION
**Pull request by dchopra001**
Signed-off-by: Dhruv Chopra <dchopra001@gmail.com>

### CODE REVIEW

**Comment by dchopra001** [comment]
@keithc-ca @pshipton Can I get a review please?

**Comment by keithc-ca** [comment]
Please update the commit message to include "by default".

**Comment by dchopra001** [comment]
I've update both PRs with the requested changes now.

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
Please also create an equivalent change for https://github.com/ibmruntimes/openj9-openjdk-jdk.

**Pull request merged**
