### PR TITLE
Several JEP424 fixes

### PR DESCRIPTION
**Pull request by keithc-ca**
* revert changes to `LayoutPath.java`
* revert changes to `X-VarHandleSegmentView.java.template`
* restore alignment checks
* remove redundant `? true : false`
* correct indentation, formatting
* compare pointers with `NULL`, not `0`
* adjust `NativeTestHelper` for AIX
* update alignments of `double`, `long` and pointers for AIX

### CODE REVIEW

**Comment by keithc-ca** [comment]
FYI @ChengJin01

**Comment by ChengJin01** [comment]
Hi @keithc-ca,  generally I'm fine with the code adjustment in this PR. Could you please create another PR with the same changes for JDKnext in https://github.com/ibmruntimes/openj9-openjdk-jdk? Or I will create one with the same changes here.

**Comment by ChengJin01** [comment]
I will need to double-check the changes on the alignment check with builds on Power (AIX & Linux) to see whether all tests passes with the code adjustments here.

**Comment by ChengJin01** [comment]
> Your comment about jdk17/18 doesn't make sense to me: the file in question (`X-VarHandleSegmentView.java.template`) only exists in jdk19/jdknext.

Yes, `X-VarHandleSegmentView.java.template` is newly introduced in JDK19+ when all elements of struct are accessed by VarHandle which requires alignment check. The corresponding alignment check flag on offset is set to `false` on JDK17/18 as the elements of `struct` can be directly accessed with offset by MemorySegment(JDK18)/MemoryAccesss (exists in JDK17/removed since JDK18), which don't require the alignment check.

**Comment by ChengJin01** [comment]
I'd like to double-check whether the alignment check via `VarHandle` is still required on JDK17/18.

**Comment by ChengJin01** [comment]
I just checked the existing struct related test case specific to AIX we already had in https://github.com/eclipse-openj9/openj9/pull/15310:
e.g. 
1) https://github.com/eclipse-openj9/openj9/blob/d39eb85f14ee06e3d03c316c5313f7bee522c4ba/test/functional/Java17andUp/src_170/org/openj9/test/jep389/upcall/UpcallMHWithMixedSigStruTests.java (JDK17)
```
public void test_addDoubleAndIntDoubleFromStructByUpcallMH() throws Throwable {
...
			/* The size of [int, double] on AIX/PPC 64-bit is 12 bytes without padding by default
			 * while the same struct is 16 bytes with padding on other platforms.
			 */
			if (isAixOS) {
				structLayout = MemoryLayout.structLayout(C_INT.withName("elem1"), C_DOUBLE.withName("elem2"));
				structSegmt = allocator.allocate(structLayout);
				MemoryAccess.setIntAtOffset(structSegmt, 0, 111111111);
				MemoryAccess.setDoubleAtOffset(structSegmt, 4, 619.777D);
			} else {
				structLayout = MemoryLayout.structLayout(C_INT.withName("elem1"),
						MemoryLayout.paddingLayout(32), C_DOUBLE.withName("elem2"));
				VarHandle elemHandle1 = structLayout.varHandle(int.class, PathElement.groupElement("elem1"));
				VarHandle elemHandle2 = structLayout.varHandle(double.class, PathElement.groupElement("elem2"));
				structSegmt = allocator.allocate(structLayout);
				elemHandle1.set(structSegmt, 111111111);
				elemHandle2.set(structSegmt, 619.777D);
			}
```
For JDK17, structs like `[int, double]` are accessed via `MemoryAccess` rather than `VarHandle` due to the alignment. We didn't add code in https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/112 given there is at least one way (`MemoryAccess`) to directly access the elements of struct in memory without alignment check if the struct layout is manually created by users

2) https://github.com/eclipse-openj9/openj9/blob/d39eb85f14ee06e3d03c316c5313f7bee522c4ba/test/functional/Java18andUp/src/org/openj9/test/jep419/upcall/UpcallMHWithMixedSigStruTests.java (JDK18)
```
public void test_addDoubleAndIntDoubleFromStructByUpcallMH() throws Throwable {
...
			/* The size of [int, double] on AIX/PPC 64-bit is 12 bytes without padding by default
			 * while the same struct is 16 bytes with padding on other platforms.
			 */
			if (isAixOS) {
				structLayout = MemoryLayout.structLayout(JAVA_INT.withName("elem1"), JAVA_DOUBLE.withName("elem2"));
			} else {
				structLayout = MemoryLayout.structLayout(JAVA_INT.withName("elem1"),
						MemoryLayout.paddingLayout(32), JAVA_DOUBLE.withName("elem2"));
			}
			VarHandle elemHandle1 = structLayout.varHandle(PathElement.groupElement("elem1"));
			VarHandle elemHandle2 = structLayout.varHandle(PathElement.groupElement("elem2"));
			MemorySegment structSegmt = allocator.allocate(structLayout);
			elemHandle1.set(structSegmt, 111111111);
			elemHandle2.set(structSegmt, 619.777D);
```
For JDK18, `VarHandle` works fine to access the elements of structs without any code changes on alignment check at https://github.com/ibmruntimes/openj9-openjdk-jdk18/pull/57.

3) https://github.com/eclipse-openj9/openj9/blob/d39eb85f14ee06e3d03c316c5313f7bee522c4ba/test/functional/Java19andUp/src/org/openj9/test/jep424/upcall/UpcallMHWithMixedSigStruTests.java (JDK19)
```
public void test_addDoubleAndIntDoubleFromStructByUpcallMH() throws Throwable {
...
			/* The size of [int, double] on AIX/PPC 64-bit is 12 bytes without padding by default
			 * while the same struct is 16 bytes with padding on other platforms.
			 */
			if (isAixOS) {
				structLayout = MemoryLayout.structLayout(JAVA_INT.withName("elem1"), JAVA_DOUBLE.withName("elem2"));
			} else {
				structLayout = MemoryLayout.structLayout(JAVA_INT.withName("elem1"),
						MemoryLayout.paddingLayout(32), JAVA_DOUBLE.withName("elem2"));
			}
			VarHandle elemHandle1 = structLayout.varHandle(PathElement.groupElement("elem1"));
			VarHandle elemHandle2 = structLayout.varHandle(PathElement.groupElement("elem2"));
			MemorySegment structSegmt = allocator.allocate(structLayout);
			elemHandle1.set(structSegmt, 111111111);
			elemHandle2.set(structSegmt, 619.777D);
```
For JDK19, the alignment check is reinforced on `VarHandle` in which case we have to modify the code involved to ensure the elements of structs are accessed correctly.

**Comment by ChengJin01** [comment]
I just finished the testing with changes in `X-VarHandleSegmentView.java.template` and there was no problem detected in the existing test cases. So I added a special test case for `[int, double, long]`  to verify:
	public void test_addDoubleAndIntDoubleLongFromStructByUpcallMH() throws Throwable {
...
			if (isAixOS) {
				structLayout = MemoryLayout.structLayout(JAVA_INT.withName("elem1"), JAVA_DOUBLE.withName("elem2"),
						JAVA_LONG.withName("elem3")); <-----
			} else {
				structLayout = MemoryLayout.structLayout(JAVA_INT.withName("elem1"),
						MemoryLayout.paddingLayout(32), JAVA_DOUBLE.withName("elem2"),
						JAVA_LONG.withName("elem3"));
			}
			VarHandle elemHandle1 = structLayout.varHandle(PathElement.groupElement("elem1"));
			VarHandle elemHandle2 = structLayout.varHandle(PathElement.groupElement("elem2"));
			VarHandle elemHandle3 = structLayout.varHandle(PathElement.groupElement("elem3")); <------------ failure occurred here when creating VarHandle for long
			MemorySegment structSegmt = allocator.allocate(structLayout);
			elemHandle1.set(structSegmt, 111111111);
			elemHandle2.set(structSegmt, 619.777D);
			elemHandle3.set(structSegmt, 888888888888L);
```
which ended up with the alignment failure as follows:
```
java.lang.UnsupportedOperationException: Invalid alignment requirements for layout J64(elem3)
        at java.base/jdk.internal.foreign.LayoutPath.checkAlignment(LayoutPath.java:250)
        at java.base/jdk.internal.foreign.LayoutPath.dereferenceHandle(LayoutPath.java:163)
        at java.base/java.lang.foreign.MemoryLayout.computePathOp(MemoryLayout.java:458)
        at java.base/java.lang.foreign.MemoryLayout.varHandle(MemoryLayout.java:387)
        at org.openj9.test.jep424.upcall.UpcallMHWithMixedSigStruTests
```
The thing is we only check alignment for float  & double in LayoutPath.java
```
    public VarHandle dereferenceHandle() {
...
        /* Ignore the alignement check for float/double on AIX/PPC to handle the case of [float/int, double]
         * given the size of [float/int, double] on AIX/PPC 64-bit is 12 bytes without padding while the
         * same struct is 16 bytes with padding on other platforms
         */
        Class<?> javaType = valueLayout.carrier();
        if (!isAixOS || ((javaType != float.class) && (javaType != double.class))) { <------
            checkAlignment(this);
        }
```
Given the alignment check is controlled by both `LayoutPath.java` (for creating VarHandle) and `X-VarHandleSegmentView.java.template` (for access to the elements of struct via `VarHandle.get()/set()`),  I think the best way is to totally ignore the alignment check on AIX in both files instead of just checking `float/double` to avoid checking unexpected combinations of structs.

**Comment by ChengJin01** [comment]
The test case with `[int/float,double]` failed as follows with the alignment check removed in `LayoutPath.java`
```
FAILED: test_addDoubleAndIntDoubleFromStructByUpcallMH
java.lang.UnsupportedOperationException: Invalid alignment requirements for layout D64(elem2)
        at java.base/jdk.internal.foreign.LayoutPath.checkAlignment(LayoutPath.java:232)
        at java.base/jdk.internal.foreign.LayoutPath.dereferenceHandle(LayoutPath.java:146)
        at java.base/java.lang.foreign.MemoryLayout.computePathOp(MemoryLayout.java:458)
        at java.base/java.lang.foreign.MemoryLayout.varHandle(MemoryLayout.java:387)
        at org.openj9.test.jep424.upcall.UpcallMHWithMixedSigStruTests.test_addDoubleAndIntDoubleFromStructByUpcallMH(UpcallMHWithMixedSigStruTests.java:178)
```
The reason for this is because simply modifying the code in `PlatformLayouts` won't affect the alignment setting for `JAVA_LONG`, `JAVA_DOUBLE` and `ADDRESS` which are actually in https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/src/java.base/share/classes/java/lang/foreign/ValueLayout.java
```
public static final OfLong JAVA_LONG = new OfLong(ByteOrder.nativeOrder())
            .withBitAlignment(64); <-----
 public static final OfDouble JAVA_DOUBLE = new OfDouble(ByteOrder.nativeOrder()).withBitAlignment(64);
public static final OfAddress ADDRESS = new OfAddress(ByteOrder.nativeOrder()) <----
            .withBitAlignment(ValueLayout.ADDRESS_SIZE_BITS); <----
```
So I will change these code in `ValueLayout` to `withBitAlignment(8)` in the case of `AIX` to see whether it works this way.

**Comment by ChengJin01** [comment]
The code at https://github.com/ChengJin01/openj9-openjdk-jdk19/commit/c37b71bb30375c692d04d86715f50c0e77883373 works fine with our own test cases specific to `[int/float, double, xxx]`, including `[int,double,long]` (no padding added in our own tests)
```
PASSED: test_addDoubleAndFloatDoubleFloatFromStructByUpcallMH
PASSED: test_addDoubleAndFloatDoubleFromStructByUpcallMH
PASSED: test_addDoubleAndFloatDoubleIntFromStructByUpcallMH
PASSED: test_addDoubleAndFloatIntDoubleFromStructByUpcallMH
PASSED: test_addDoubleAndIntDoubleFloatFromStructByUpcallMH
PASSED: test_addDoubleAndIntDoubleFromStructByUpcallMH
PASSED: test_addDoubleAndIntDoubleIntFromStructByUpcallMH
PASSED: test_addDoubleAndIntDoubleLongFromStructByUpcallMH
```

But there a couple test failure in jtreg test with `[int/float, double,xxx]`. e.g. for [`int,double,int]
```
test TestDowncallScope.testDowncall(11033, "f18_S_SDD_IDI", NON_VOID, [STRUCT, DOUBLE, DOUBLE], [INT, D
OUBLE, INT]): failure
java.lang.IllegalStateException: java.lang.AssertionError: expected [42] but found [0]
        at CallGeneratorHelper.lambda$initStruct$10(CallGeneratorHelper.java:443)
        at TestDowncallScope.lambda$testDowncall$0(TestDowncallScope.java:74)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at TestDowncallScope.testDowncall(TestDowncallScope.java:74)
```
The padding of struct is calculated & added based on `bitAlignment()`  in the test via https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/test/jdk/java/foreign/CallGeneratorHelper.java
```
MemoryLayout layout(List<StructFieldType> fields) {
            if (this == STRUCT) {
                long offset = 0L;
                List<MemoryLayout> layouts = new ArrayList<>();
                long align = 0;
                for (StructFieldType field : fields) {
                    MemoryLayout l = field.layout();
                    long padding = offset % l.bitAlignment(); <-------
                    if (padding != 0) {
                        layouts.add(MemoryLayout.paddingLayout(padding));
                        offset += padding;
                    }
                    layouts.add(l.withName("field" + offset));
                    align = Math.max(align, l.bitAlignment());
                    offset += l.bitSize();
                }
                long padding = offset % align;
                if (padding != 0) {
                    layouts.add(MemoryLayout.paddingLayout(padding));
                }
                return MemoryLayout.structLayout(layouts.toArray(new MemoryLayout[0]));
            } else {
                return layout;
            }
        }
```
Given the alignment for `double` is set to 8bits, I am wondering whether the padding was still added to `[int,double,int]` in the test based on the test code above. If so, probably 8bits is still inappropriate; otherwise, we should modify the test to avoid the padding in such case.

**Comment by ChengJin01** [comment]
I double-checked the test code at https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/test/jdk/java/foreign/CallGeneratorHelper.java as follows:
```
    enum StructFieldType {
        INT("int", C_INT),
        FLOAT("float", C_FLOAT),
        DOUBLE("double", C_DOUBLE), <-------- not JAVA_DOUBLE
        POINTER("void*", C_POINTER);

....
 MemoryLayout layout(List<StructFieldType> fields) { <--------
            if (this == STRUCT) {
                long offset = 0L;
                List<MemoryLayout> layouts = new ArrayList<>();
                long align = 0;
                for (StructFieldType field : fields) {
                    MemoryLayout l = field.layout();
                    long padding = offset % l.bitAlignment();
```
I suspect the test code still replies on `C_DOUBLE` rather than `JAVA_DOUBLE`, in which case only changing the alignment of double has no impact on `C_DOUBLE` in this test. So I will try to modify the `C_DOUBLE` layout on AIX at https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/master/src/java.base/share/classes/jdk/internal/foreign/PlatformLayouts.java
```
       public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE.withBitAlignment(64);
```
to 
```
       public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE.withBitAlignment(8);
```
to see how it goes this way.

**Comment by ChengJin01** [comment]
It turns out that the test suite relies on the test native layout helper at https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/test/jdk/java/foreign/NativeTestHelper.java to set up the layout in tests rather than https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/master/src/java.base/share/classes/jdk/internal/foreign/PlatformLayouts.java
```
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG.withBitAlignment(64); <---

    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE.withBitAlignment(64); <----

    public static final ValueLayout.OfAddress C_POINTER = ValueLayout.ADDRESS.withBitAlignment(64); <----
```

With the updated test code in `NativeTestHelper.java` at https://github.com/ChengJin01/openj9-openjdk-jdk19/commit/f1f4fec91ff055d7dd7ab9c0dedf56317f9336a8, the test suite passed as expected. e.g.
```
test TestDowncallScope.testDowncall(34, "f0_V_S_IDF", VOID, [STRUCT], [INT, DOUBLE, FLOAT]): success
test TestDowncallScope.testDowncall(51, "f0_V_S_FDD", VOID, [STRUCT], [FLOAT, DOUBLE, DOUBLE]): success
test TestDowncallScope.testDowncall(1037, "f1_V_IDI_", VOID, [INT, DOUBLE, INT], []): success
test TestDowncallScope.testDowncall(1071, "f1_V_IDS_IDD", VOID, [INT, DOUBLE, STRUCT], [INT, DOUBLE, DOU
BLE]): success
test TestDowncallScope.testDowncall(1088, "f1_V_IDS_FDP", VOID, [INT, DOUBLE, STRUCT], [FLOAT, DOUBLE, P
OINTER]): success
test TestDowncallScope.testDowncall(1173, "f1_V_IPS_FDI", VOID, [INT, POINTER, STRUCT], [FLOAT, DOUBLE,
INT]): success
test TestDowncallScope.testDowncall(1258, "f2_V_ISI_FDF", VOID, [INT, STRUCT, INT], [FLOAT, DOUBLE, FLOA
T]): success
...
```

**Comment by ChengJin01** [comment]
@keithc-ca, please update this PR with my changes in https://github.com/ChengJin01/openj9-openjdk-jdk19/commit/f1f4fec91ff055d7dd7ab9c0dedf56317f9336a8 or I can create another PR with my changes if you prefer to do separately.

**Comment by ChengJin01** [comment]
As discussed with @keithc-ca, we think `32bit` rather than `8bit` should be more appropriate in terms of `long_long`/`double`/`pointer` based on a sample test in native for layouts. As such, I will create a build with this to verify in tests.

**Comment by ChengJin01** [comment]
The double related tests in our own test suite failed with the updated changes at https://github.com/keithc-ca/openj9-openjdk19/commit/849bb446d4740e4fd2c96dc3eadfa7c2aea06b50. e.g.
```
public void test_addDoubleAndFloatDoubleFloatFromStructByUpcallMH() throws Throwable {
		GroupLayout structLayout = isAixOS ? MemoryLayout.structLayout(JAVA_FLOAT.withName("elem1"),
				JAVA_DOUBLE.withName("elem2").withBitAlignment(32), JAVA_FLOAT.withName("elem3"))
				: MemoryLayout.structLayout(JAVA_FLOAT.withName("elem1"),
						MemoryLayout.paddingLayout(32), JAVA_DOUBLE.withName("elem2"),
						JAVA_FLOAT.withName("elem3"));
		VarHandle elemHandle1 = structLayout.varHandle(PathElement.groupElement("elem1"));
		VarHandle elemHandle2 = structLayout.varHandle(PathElement.groupElement("elem2"));
		VarHandle elemHandle3 = structLayout.varHandle(PathElement.groupElement("elem3"));
...
			elemHandle1.set(structSegmt, 11.222F);
			elemHandle2.set(structSegmt, 218.555D);
			elemHandle3.set(structSegmt, 33.444F);

	public static double addDoubleAndFloatDoubleFloatFromStruct(double arg1, MemorySegment arg2) { <-- failed to access double in arg2
		double structElem2 = (isAixOS) ? arg2.get(JAVA_DOUBLE, 4) : arg2.get(JAVA_DOUBLE, 8);
		float structElem3 = (isAixOS) ? arg2.get(JAVA_FLOAT, 12) : arg2.get(JAVA_FLOAT, 16);
		double doubleSum = arg1 + structElem1 + structElem2 + structElem3;
		return doubleSum;
	}

FAILED: test_addDoubleAndFloatDoubleFloatFromStructByUpcallMH
java.lang.IllegalArgumentException: Misaligned access at address: 1099780701532
        at java.base/java.lang.invoke.VarHandleSegmentViewBase.newIllegalArgumentExceptionForMisalignedAccess(VarHandleSegmentViewBase.java:57)
        at java.base/java.lang.invoke.VarHandleSegmentAsDoubles.offsetNoVMAlignCheck(VarHandleSegmentAsDoubles.java:107)
        at java.base/java.lang.invoke.VarHandleSegmentAsDoubles.get(VarHandleSegmentAsDoubles.java:118)
        at java.base/java.lang.foreign.MemorySegment.get(MemorySegment.java:1404)
        at org.openj9.test.jep424.upcall.UpcallMethodHandles.addDoubleAndFloatDoubleFloatFromStruct(UpcallMethodHandles.java:1848)
        at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.invokeNative(Native Method)
        at java.base/openj9.internal.foreign.abi.InternalDowncallHandler.runNativeMethod(InternalDowncallHandler.java:572)
        at org.openj9.test.jep424.upcall.UpcallMHWithMixedSigStruTests.test_addDoubleAndFloatDoubleFloatFromStructByUpcallMH(UpcallMHWithMixedSigStruTests.java:817)

```
The failing test above uses `VarHandle` to set the value the double for `JAVA_DOUBLE.withName("elem2").withBitAlignment(32)` in the struct [float, double, float] (which works fine) while accessing the double value via `MemorySegment.set()` (which depends on the code in `X-VarHandleSegmentView.java.template` to do the alignment check). It means we have to restore the changes on `X-VarHandleSegmentView.java.template` to ensure the elements of struct can be accessed this way.

Meawhile, the test passed if the upcall method is modified to access `double` via VarHandle.
```
	public static double addDoubleAndFloatDoubleFloatFromStruct(double arg1, MemorySegment arg2) {
		GroupLayout structLayout = isAixOS ? MemoryLayout.structLayout(JAVA_FLOAT.withName("elem1"),
				JAVA_DOUBLE.withName("elem2").withBitAlignment(32), JAVA_FLOAT.withName("elem3"))
				: MemoryLayout.structLayout(JAVA_FLOAT.withName("elem1"),
						MemoryLayout.paddingLayout(32), JAVA_DOUBLE.withName("elem2"),
						JAVA_FLOAT.withName("elem3"));
		VarHandle elemHandle1 = structLayout.varHandle(PathElement.groupElement("elem1"));
		VarHandle elemHandle2 = structLayout.varHandle(PathElement.groupElement("elem2"));
		VarHandle elemHandle3 = structLayout.varHandle(PathElement.groupElement("elem3"));

		double doubleSum = arg1 + (float)elemHandle1.get(arg2) + (double)elemHandle2.get(arg2) + (float)elemHandle3.get(arg2);;
		return doubleSum;
	}
```
That is to say, we still need to the previous changes in `X-VarHandleSegmentView.java.template` to support both `MemorySegment.get()/set()` and `VarHandle.get()/set()` in accessing the elements of struct.

In addition, the jtreg test suite mentioned at https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/15#issuecomment-1195679675 still passed without any issue with the latest changes in `NativeTestHelper.java`
```
test TestDowncallScope.testDowncall(34, "f0_V_S_IDF", VOID, [STRUCT], [INT, DOUBLE, FLOAT]): success
...
```

**Comment by ChengJin01** [comment]
It turns out that `MemorySegment.get()/set()` still follows the rules of `JAVA_DOUBLE` in the same way as `VarHandle` in which case the double of the upcall mehod in the failing test `[float,double,float]` above should be accessed via `JAVA_DOUBLE.withBitAlignment(32)` as follows: (users should be aware of this when accessing elements of stuct via MemorySegment.get/set  on AIX on JDK19+)
```
	public static double addDoubleAndFloatDoubleFloatFromStruct(double arg1, MemorySegment arg2) {
		float structElem1 = arg2.get(JAVA_FLOAT, 0);
		/* The size of [float, double, float] on AIX/PPC 64-bit is 16 bytes without padding by default
		 * while the same struct is 20 bytes with padding on other platforms.
		 */
		double structElem2 = (isAixOS) ? arg2.get(JAVA_DOUBLE.withBitAlignment(32), 4) <------------------------
		: arg2.get(JAVA_DOUBLE, 8);
		float structElem3 = (isAixOS) ? arg2.get(JAVA_FLOAT, 12) : arg2.get(JAVA_FLOAT, 16);
		double doubleSum = arg1 + structElem1 + structElem2 + structElem3;
		return doubleSum;
	}
```
I verified this which works good as expected. So there should be no more change required in https://github.com/keithc-ca/openj9-openjdk19/commit/849bb446d4740e4fd2c96dc3eadfa7c2aea06b50.

**Comment by keithc-ca** [comment]
Rebased and updated as mentioned in https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/15#issuecomment-1196095893.
The copyright check failures are expected as this reverts those files from upstream.

**Comment by tajila** [comment]
jenkins test sanity plinux jdk19

**Review by tajila — APPROVED** [review]

**Pull request merged**
