### PR TITLE
Remove unused scripts

### PR DESCRIPTION
**Pull request by keithc-ca**
The jenkins jobs are configured to use the jdknext repository.

This is a cherry-pick of ibmruntimes/openj9-openjdk-jdk18#56.

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Jenkins line endings check

**Comment by AdamBrousseau** [comment]
Jenkins signed off by check

**Comment by AdamBrousseau** [comment]
Jenkins compile zlinux jdk19

**Comment by JasonFengJ9** [comment]
```
17:49:52  TESTS_TARGETS:'none'
[Pipeline] echo
17:49:52  RELEASES:'[19]'
[Pipeline] echo
17:49:52  PLATFORMS:'[s390x_linux]'
[Pipeline] echo
17:49:52  RELEASES:'[19]'
[Pipeline] echo
17:49:52  PLATFORMS:'[s390x_linux]'
[Pipeline] echo
17:49:52  Warning: Selected Java versions (19) for s390x_linux is not supported(nothing to do)!
[Pipeline] error
[Pipeline] cleanWs
17:49:52  [WS-CLEANUP] Deleting project workspace...
17:49:52  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
17:49:52  [WS-CLEANUP] done
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] echo
Time spent fetching downstream jobs for PullRequest-OpenJDK19: 0 seconds
[Pipeline] End of Pipeline
ERROR: Invalid PLATFORMS (null) and/or Java versions selections(19)!
```

**Comment by pshipton** [comment]
Created https://github.com/eclipse-openj9/openj9/pull/15318

**Comment by pshipton** [comment]
Jenkins compile zlinux jdk19

**Review by AdamBrousseau — APPROVED** [review]

**Pull request merged**
