### PR TITLE
Enable vm.continuations option for testing

### PR DESCRIPTION
**Pull request by fengxue-IS**
Depends: https://github.com/adoptium/aqa-tests/pull/4087

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by fengxue-IS** [comment]
@LongyuZhang Can you take a look, note this depends on aqa-test changes that disable extended.openjdk tests failures in serviceability suite

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Comment by fengxue-IS** [comment]
@pshipton Can you please take a look.
sanity.openjdk tests related to VirtualThread/Continuation will be re-enabled via https://github.com/adoptium/aqa-tests/pull/4060

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
@fengxue-IS what's the plan for jdk20?

**Comment by fengxue-IS** [comment]
> @fengxue-IS what's the plan for jdk20?

I will run a grinder to verify if sanity/extended also passes for JDK20, if so, I will port this change to jdknext

**Pull request merged**
