### PR TITLE
Port CRIU related PRs from openj9-openjdk-jdk17 and handle thread interrupted status at CRIU single threaded mode

### PR DESCRIPTION
**Pull request by JasonFengJ9**
Cherry-pick CRIU related PRs from [openj9-openjdk-jdk17](https://github.com/ibmruntimes/openj9-openjdk-jdk17)
* https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/110
* https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/111
* https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/128

Note: following PRs have already been ported
* https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/84
* https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/87 which was cherry-pick of https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/486 & https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/498

Added [Handle thread interrupted status at CRIU single threaded mode](https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/54/commits/c569e9e8668deb5e8a6f5b556c4912c834282611) to address delayed `Thread.interrupt()` at CRIU single threaded mode.

depends on https://github.com/eclipse-openj9/openj9/pull/16470

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
Jenkins test sanity xlinux,xlinuxcriu jdk19

**Comment by keithc-ca** [comment]
@tajila Can you please weigh in on the CRIU test failures.

**Comment by JasonFengJ9** [comment]
> [OUT] TestDelayedOperations.testDelayedThreadInterrupt(): FAILED at PreCheckpointHook()
 [OUT] TestDelayedOperations.testDelayedThreadInterrupt(): FAILED at PostSnapshotHook()

Looking into these failures.

**Comment by JasonFengJ9** [comment]
This is because JDK19 set `interrupted` before invoking `interruptImpl()`, so `isInterrupted()` returns `true` even CRIU holds the `interruptImpl()`.
```
            interrupted = true;
            interrupt0();  // inform VM of interrupt
```
If we decide no change required for this thread behaviour, the test is invalid for JDK19 since `isInterrupted()` can't accurately tell if the `interruptImpl()` has been delayed or not.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/d78ba9640fed4fc0b5cda490a2ac8c2f21622059/src/java.base/share/classes/java/lang/Thread.java#L1758-L1759

**Comment by JasonFengJ9** [comment]
Added [Handle thread interrupted status at CRIU single threaded mode](https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/54/commits/c569e9e8668deb5e8a6f5b556c4912c834282611) to address delayed `Thread.interrupt()` at CRIU single threaded mode.

FYI @tajila

**Comment by tajila** [comment]
Jenkins test sanity xlinux,xlinuxcriu jdk19

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
@JasonFengJ9 please make the jdknext changes

**Comment by JasonFengJ9** [comment]
Created https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/533
@tajila please review.

**Pull request merged**
