### PR TITLE
Fix SelfSuspendDisablerTest

### PR DESCRIPTION
**Pull request by babsingh**
See https://github.com/eclipse-openj9/openj9/issues/16276#issuecomment-1310908446.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by babsingh** [comment]
Grinder (https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29486/) shows that `SelfSuspendDisablerTest` passes with this PR. There is one failure:
```
### serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java

11:25:47  *** Invalid JIT return address 000003FF607AA18C in 000003FFA627E1B0
11:25:47  
11:25:47  16:25:40.058 0x3ff0c002200    j9vm.249    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/Build_JDK19_s390x_linux_Personal/openj9/runtime/vm/swalk.c:1632: ((0 ))
```
But, it is unrelated to this PR, and a known failure: https://github.com/eclipse-openj9/openj9/issues/16249.

**Comment by babsingh** [comment]
@tajila can you please review?

**Comment by babsingh** [comment]
JDK-next PR: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/524

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
jenkins test sanity amac jdk19

**Pull request merged**
